### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by shusei996** [kunichiko/MS2109-mono-to-stereo-mac#2]
“brew install kunichiko/tap/mono2stereo” ended with error message below.
Could you help to solve it ?

macOS : 13.2
Xcode : 14.2

swift build -c release --disable-sandbox
warning: /Users/xxxxxx/Library/org.swift.swiftpm/configuration is not accessible or not writable, disabling user-level configuration features.
warning: /Users/xxxxxx/Library/org.swift.swiftpm/security is not accessible or not writable, disabling user-level security features.
warning: /Users/xxxxxx/Library/Caches/org.swift.swiftpm is not accessible or not writable, disabling user-level cache features.
warning: 'ms2109-mono-to-stereo-mac-0.9.1': failed loading cached manifest for 'ms2109-mono-to-stereo-mac-0.9.1': Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “manifests” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/xxxxxx/Library/Caches/org.swift.swiftpm/manifests, NSUnderlyingError=0x600003559260 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: 'ms2109-mono-to-stereo-mac-0.9.1': failed closing cache: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “manifests” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/xxxxxx/Library/Caches/org.swift.swiftpm/manifests, NSUnderlyingError=0x600003553e70 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error: 'ms2109-mono-to-stereo-mac-0.9.1': Invalid manifest
/private/tmp/mono2stereo-20230210-2273-1dju8dk/MS2109-mono-to-stereo-mac-0.9.1/Package.swift:4:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
make: *** [build] Error 1

**Comment by RevoltEnergy** [comment]
same issue

**Comment by kunichiko** [comment]
Thank you for your feedback. I will try to fix this problem next weekend!

**Comment by shusei996** [comment]
thank you for your support!!

**Comment by ctf4bba** [comment]
same issue

**Comment by kunichiko** [comment]
@shusei996 @RevoltEnergy 
I apologize for the delayed response.

Although I was unable to reproduce the error for several weeks, I was able to do so now by installing a clean macOS 13.2 in a virtual machine on Parallels.

Please execute the command below in your environment:

```
> xcode-select -p
```

If the output is `/Library/Developer/CommandLineTools` , you should change the active developer directory to Xcode's path, as shown below:

```
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

* This example assumes Xcode was installed in /Applications/Xcode.app. If it was installed in a different path, please adjust the command accordingly.

After completing this step, you should be able to successfully build mono2stereo.

**Comment by shusei996** [comment]
I could successfully built it and audio can be stereo. 
Thank you!!
However, sometime no audio, sometime fine even it is the same setting (I think…).
It may be due to my environment, I try to fix it.
